Added Settings Fragment as Preferences.
fossasia/neurolab-android pull request #18
Opened 2019-01-01 16:17 UTC by jddeep

Screenshot of the SettingsFragment -
![firstpullreqneurolab](https://user-images.githubusercontent.com/43133646/50574417-5894f980-0e0e-11e9-9cca-8f1a114898a4.jpeg)
Fixes #[Add issue number here. Note: This will automatically closes the issue. If you do not solve the issue entirely, please change the message to e.g. "First steps for issues #IssueNumber]

**Changes**: [Add here what changes were made in this issue and if possible provide links.]

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

2019-01-01 18:16 UTC, mariobehling commented
Thank you. Please add issue number and ensure Travis builds.

2019-01-02 01:34 UTC, CloudyPadmal requested changes
Thank you for the PR. Please change the name `BCI` to `Neuro` in every instance. Reformat the code and remove all the extra new lines and spaces added.

2019-01-02 01:34 UTC, CloudyPadmal commented on app/build.gradle
> +    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
This is added in line 29

2019-01-02 01:34 UTC, CloudyPadmal commented on app/build.gradle
> +    implementation 'com.android.support:preference-v7:26.1.0'
Use the same library version across the whole project. Change this to;
`implementation "com.android.support:preference-v7:$rootProject.supportLibraryVersion"`

2019-01-02 01:34 UTC, CloudyPadmal commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".BCISettingsActivity"></activity>
This is not BCI. Change **BCI** to **Neuro**

2019-01-02 01:34 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/BCISettings.java
> +@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
We need to support from API level 16

2019-01-02 01:34 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/BCISettings.java
> +    //@TODO
Remove

2019-01-02 01:34 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/BCISettings.java
> +
Remove excess spacing

2019-01-02 01:34 UTC, CloudyPadmal commented on app/src/main/res/values/styles.xml
> +
Please do not add extra new lines like this

2019-01-02 01:34 UTC, CloudyPadmal commented on app/src/main/res/xml/bci_settings_fragment.xml
> +        />
Reformat the code using [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>], Keep the `/>` at the end of the last parameter instead on a new line.

2019-01-02 04:44 UTC, jddeep commented
There were some better changes to be made to resolve the issue which I understood later. I will make the corrected pull request again.

2019-01-02 04:44 UTC, closed without merging

2019-01-02 04:44 UTC, jddeep commented
There were some better changes to be made to resolve the issue which I understood later. I will make the corrected pull request again.

2019-01-02 12:50 UTC, CloudyPadmal commented
Please don't close PRs and open another one with the changes. We need to follow up on the progress. Similar issues I have reviewed here still exist in that PR. Now I have to comment all over again on a brand new PR. Please double check first.

Those issues you have opened #20 #21 are issues in your PR, not in the main repository. No need to open issues like that.

2019-01-02 13:08 UTC, jddeep commented
Okay I will make sure about that @CloudyPadmal  from next time. But rest assure i closed the issues #20 and #21 and made all the changes that were required and now the new PR is completely mergeable.