Implemented the NeuroGameRenderer class
fossasia/neurolab-android pull request #201
Opened 2019-05-14 16:50 UTC by suresh-gandhi

Fixes #174 partly (Checklist point - 4)

**Changes**: 
* Implemented the class NeuroGameRenderer (belonging to the output.visual package) in the Android version.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-05-14 17:21 UTC, suresh-gandhi commented
@mariobehling @CloudyPadmal Could you please review the PR?

2019-05-15 04:35 UTC, CloudyPadmal approved these changes

2019-05-15 12:42 UTC, suresh-gandhi commented
@CloudyPadmal Does something needs to be changed or it can be merged?

2019-05-16 03:07 UTC, jddeep requested changes

2019-05-16 03:07 UTC, jddeep commented on app/src/main/java/io/neurolab/main/output/visual/NeuroGameRenderer.java
> +            offsetY = height / 2;
@suresh-gandhi I think these are again UI related. Should be done when we code the Fragments.

2019-05-16 03:09 UTC, jddeep reviewed
@suresh-gandhi Have a revision of the whole class and remove all UI related actions.

2019-05-16 06:05 UTC, suresh-gandhi commented
@jddeep You are correct about the UI and base functionality separation but these classes are rendering classes (using the open GL library) themselves as you can see. Thanks for your review.

2019-05-16 08:12 UTC, suresh-gandhi commented
@CloudyPadmal @mariobehling Could you please review and merge the PR.

2019-05-16 08:33 UTC, jddeep commented
> @jddeep You are correct about the UI and base functionality separation but these classes are rendering classes (using the open GL library) themselves as you can see. Thanks for your review.

Alright @suresh-gandhi we can keep it for now. Will update accordingly when we start working on UX/UI.

2019-05-16 08:34 UTC, jddeep approved these changes

2019-05-16 08:37 UTC, merged