Implemented the AudioFeedback base class
fossasia/neurolab-android pull request #202
Opened 2019-05-15 13:24 UTC by suresh-gandhi

Fixes #171.

**Changes**: 
* Implemented the AudioFeedback base class (belonging to the output.audio package) in Android version.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-05-15 13:34 UTC, suresh-gandhi commented
@CloudyPadmal @mariobehling Could you please review the PR. Let me know if something needs to be changed. Thanks.

2019-05-15 14:35 UTC, ShridharGoel commented
There are some unused fields and other issues as pointed out by Codacy. Please try to fix them.

2019-05-15 14:41 UTC, jddeep requested changes

2019-05-15 14:41 UTC, jddeep commented on app/src/main/java/io/neurolab/main/output/audio/AudioFeedback.java
> +    private int windowSize = 400;
I think these parameters are much related to the UI for the Feedback. No need of these in the base class. We can make UI related changes in the Activity and Fragment @suresh-gandhi .

2019-05-15 14:41 UTC, jddeep commented on app/src/main/java/io/neurolab/main/output/audio/AudioFeedback.java
> +        colorImage = BitmapFactory.decodeFile(ResourceManager.getInstance().getResource(context, "4colors.jpg").getAbsolutePath());
Same here. We can make UI related changes in the Activity/Fragment.

2019-05-15 14:43 UTC, jddeep commented
@suresh-gandhi Just go through the whole class once and keep only functionality related changes here in the base class. Because that will help us when we design and develop the UI. 🚀

2019-05-15 17:30 UTC, suresh-gandhi commented
@jddeep Thanks for your review. I removed android.graphics usages (to be reserved for UI Activity/Fragment class). However, volume, max volume and other variables are being loaded from the Resource Manager class here and even getting modified at some places. Hence I have added getters for them to be directly accessed by the UI class and use them for display.

2019-05-16 03:02 UTC, jddeep approved these changes
@suresh-gandhi Good job 👍

2019-05-16 08:12 UTC, suresh-gandhi commented
@CloudyPadmal @mariobehling Could you please review and merge the PR.

2019-05-16 08:36 UTC, CloudyPadmal approved these changes

2019-05-16 08:37 UTC, merged