Implemented OSCForwardTask and made updations to NFBServer
fossasia/neurolab-android pull request #218
Opened 2019-05-17 07:41 UTC by jddeep

Fixes #209 

**Changes**: Implemented OSCForwardTask and made updations to NFBServer.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

2019-05-17 07:44 UTC, mariobehling approved these changes

2019-05-17 07:45 UTC, jddeep commented
@mariobehling Please don't merge this right now. Let me implement the OSCForwardMask before this.

2019-05-17 17:40 UTC, suresh-gandhi approved these changes

2019-05-17 17:45 UTC, suresh-gandhi requested changes

2019-05-17 17:45 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/NFBServer.java
> +    }
@jddeep Everything looks good. Just rearrange the code. Getters and setters should be below.

2019-05-17 17:45 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/NFBServer.java
> +
@jddeep remove the extra space of line.

2019-05-17 17:45 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/task/OscForwardTask.java
> +    private int forwardMode = 0;
@jddeep here as well rearrange the code.

2019-05-17 17:45 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/task/OscForwardTask.java
> +
remove an extra line of space from here as well.

2019-05-17 17:45 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/task/OscForwardTask.java
> +
here also

2019-05-17 17:45 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/task/OscForwardTask.java
> +
.

2019-05-19 08:51 UTC, suresh-gandhi approved these changes

2019-05-20 13:05 UTC, merged