Implemented LongtermFFTVisualizer base
fossasia/neurolab-android pull request #223
Opened 2019-05-18 04:53 UTC by jddeep

Fixes #210 

**Changes**: Implemented LongtermFFTVisualizer base.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

2019-05-18 19:39 UTC, suresh-gandhi requested changes
@jddeep Everything is good to go. Just needs a bit of reformatting and rearranging.

2019-05-18 19:39 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/output/visual/LongtermFFTVisualizer.java
> +
Remove an extra space of line from here.

2019-05-18 19:39 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/output/visual/LongtermFFTVisualizer.java
> +            for (int c = 0; c < numChannels; c++)
here also

2019-05-18 19:39 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/output/visual/LongtermFFTVisualizer.java
> +
here also.

2019-05-18 19:39 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/output/visual/LongtermFFTVisualizer.java
> +
here

2019-05-18 19:39 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/output/visual/LongtermFFTVisualizer.java
> +
here

2019-05-18 19:39 UTC, suresh-gandhi commented on app/src/main/java/io/neurolab/main/output/visual/LongtermFFTVisualizer.java
> +    int[] sampleCounter;
Rearrange the code - variables top and methods below

2019-05-19 00:47 UTC, jddeep commented
@suresh-gandhi Done the formatting changes,

2019-05-19 05:23 UTC, mariobehling approved these changes

2019-05-19 05:23 UTC, merged