Implemented the NFBGraph class
fossasia/neurolab-android pull request #238
Opened 2019-05-21 19:02 UTC by suresh-gandhi

Fixes #224.

**Changes**: 
* Implemented the NFBGraph class (belonging to the main subpackage) in Android version.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-05-22 17:24 UTC, suresh-gandhi commented
@jddeep Could you review.

2019-05-23 01:45 UTC, jddeep requested changes

2019-05-23 01:45 UTC, jddeep commented on app/src/main/java/io/neurolab/main/NFBGraph.java
> +
@suresh-gandhi Avoid writing empty public methods. Either comment the future motive or perform some action in it.

2019-05-23 23:19 UTC, suresh-gandhi commented
@CloudyPadmal @mariobehling Could you please review and merge. Peer review is done.

2019-05-24 00:57 UTC, adityastic approved these changes

2019-05-24 07:51 UTC, merged