Implemented the SerialForwardTask class
fossasia/neurolab-android pull request #239
Opened 2019-05-21 19:42 UTC by suresh-gandhi

Fixes #221 which completes the porting of main.task subpackage.

**Changes**: 
* Implemented the SerialForwardTask in Android version.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-05-22 01:40 UTC, jddeep requested changes

2019-05-22 01:40 UTC, jddeep commented on app/src/main/java/io/neurolab/main/task/SerialForwardTask.java
> +        System.err.println("init osc forward");
@suresh-gandhi Use Log.e instead

2019-05-23 01:46 UTC, jddeep requested changes

2019-05-23 01:46 UTC, jddeep commented on app/src/main/java/io/neurolab/main/task/SerialForwardTask.java
> +
@suresh-gandhi Avoid writing empty public methods. Either comment the future motive or perform some action in it.

2019-05-23 23:18 UTC, suresh-gandhi commented
@CloudyPadmal @mariobehling Could you please review and merge. Peer review is done.

2019-05-24 00:56 UTC, adityastic approved these changes

2019-05-24 07:50 UTC, merged