Fixed UX/UI autorotation bug
fossasia/neurolab-android pull request #275
Opened 2019-05-31 15:33 UTC by jddeep

Fixes #272 

**Changes**: Fixed UX/UI Autorotation bug.

**Screenshot/s for the changes**: 

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:

2019-05-31 15:43 UTC, jddeep commented
@suresh-gandhi Can I get a peer review? Thanks.

2019-05-31 16:13 UTC, CloudyPadmal approved these changes

2019-06-01 06:02 UTC, suresh-gandhi requested changes

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                android:id="@+id/view"
@jddeep use more descriptive (rather than generic) names for ids always.

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                android:id="@+id/view2"
here as well

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                app:layout_constraintHorizontal_bias="0.739"
dont hardcode the values

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                app:layout_constraintVertical_bias="0.0" />
here

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                app:layout_constraintGuide_percent="0.21" />
here

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                app:layout_constraintGuide_percent="0.66" />
here and also at other places

2019-06-01 06:02 UTC, suresh-gandhi commented on app/src/main/res/layout-land/content_main.xml
> +                android:id="@+id/textView3"
descriptive id names

2019-06-01 12:47 UTC, jddeep commented
Done the formatting changes. 👍

2019-06-01 17:40 UTC, suresh-gandhi approved these changes

2019-06-02 00:53 UTC, merged