Revamping the UX/UI of the Launcher Screen
fossasia/neurolab-android pull request #279
Opened 2019-06-04 11:27 UTC by jddeep

Fixes #276 

**Changes**: Revamping the UX/UI of the Launcher Screen

**Screenshot/s for the changes**:

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:

2019-06-04 11:31 UTC, jddeep commented
@CloudyPadmal The basic structure is ready. Need to make a few more design tweaks and updates overall. After that, we will be good to go.

2019-06-04 11:34 UTC, jddeep commented
@adityastic I saw you are good at designing. I have got an interesting job for you :D Can you design specific program mode images/icons for 4 cards in the launcher. (See in the screenshot, have used the same image for every card)

2019-06-04 11:47 UTC, adityastic commented
@jddeep don't worry, I'll take care of the icons. But change the design of the cards, try to shift the icon on the left side and the title and subtitle on the other. It will be more consistent

2019-06-04 11:48 UTC, adityastic commented
I'll also design the background for the cards as well. Give me some time, I'll be back home in 3 hrs

2019-06-04 11:51 UTC, jddeep commented
> @jddeep don't worry, I'll take care of the icons. But change the design of the cards, try to shift the icon on the left side and the title and subtitle on the other. It will be more consistent

Yeah i know. I have just got the structure ready. Need to make some final tweaks.

2019-06-04 12:16 UTC, CloudyPadmal commented
> > @jddeep don't worry, I'll take care of the icons. But change the design of the cards, try to shift the icon on the left side and the title and subtitle on the other. It will be more consistent
> 
> Yeah i know. I have just got the structure ready. Need to make some final tweaks.

Make a PR when everything is ready.

2019-06-04 15:34 UTC, suresh-gandhi requested changes

2019-06-04 15:34 UTC, suresh-gandhi commented on app/src/main/res/layout/content_main.xml
> +                    android:layout_height="80dp"
remove the hardcoded value

2019-06-04 15:34 UTC, suresh-gandhi commented on app/src/main/res/layout/content_main.xml
> +                    android:padding="10dp"
here also

2019-06-04 15:34 UTC, suresh-gandhi commented on app/src/main/res/layout/content_main.xml
> +                    android:textSize="18sp" />
here and everywhere else

2019-06-04 15:50 UTC, adityastic commented
@jddeep change the status to WIP

2019-06-04 15:56 UTC, adityastic reviewed
@jddeep change the title to WIP

2019-06-05 13:06 UTC, jddeep commented
WIP
![Screenshot_20190605-183404](https://user-images.githubusercontent.com/43133646/58958501-a8faf380-87c0-11e9-85ca-21661d0ca346.png)
Will finalize once #280 get's done.

2019-06-05 13:50 UTC, adityastic commented
@jddeep no, don't do this. Let me design the rest of the cards for you. Also the actionbar does not match the card theme

2019-06-05 14:12 UTC, jddeep commented
> @jddeep no, don't do this. Let me design the rest of the cards for you. Also the actionbar does not match the card theme

@adityastic Yes. If you see I haven't made any commit xD. Will do once everything is finished. Just commented for an update as WIP.

2019-06-05 14:31 UTC, adityastic commented
Oh xD great

2019-06-05 16:09 UTC, CloudyPadmal commented
@adityastic why don't you send a direct PR with image resources? :thinking:

2019-06-05 16:14 UTC, adityastic commented
@CloudyPadmal sounds better to me xD. @jddeep let me send a pr with the complete design change

2019-06-05 16:15 UTC, adityastic commented
@CloudyPadmal sounds better to me xD

2019-06-06 04:28 UTC, jddeep commented
> @adityastic why don't you send a direct PR with image resources? 🤔

Yup that was basically even the #280 description xD

2019-06-07 16:08 UTC, jddeep commented
@suresh-gandhi Peer review please :D

2019-06-07 16:59 UTC, CloudyPadmal approved these changes

2019-06-07 20:09 UTC, mariobehling approved these changes

2019-06-07 20:09 UTC, mariobehling commented
Good job!

2019-06-07 20:09 UTC, merged