Added some initial datasets
fossasia/neurolab-android pull request #293
Opened 2019-06-12 23:11 UTC by suresh-gandhi

Fixes #288 partly.

**Changes**: 
* Added a couple of datasets:  [Confused Student EEG brainwave data](https://www.kaggle.com/wanghaohan/confused-eeg) and the neurolab-desktop data.
* A description markdown file is added alongside to give an overview.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

2019-06-12 23:59 UTC, suresh-gandhi commented
@CloudyPadmal Could you please cross verify this data-set and let me if its the correct direction? I found this data set to be relevant and related (for projecting out the confused state of mind for instance). Meanwhile, I am trying to figure out what caused this building fail ambiguity.

2019-06-13 01:45 UTC, CloudyPadmal requested changes
Remove the k24bit.csv file as it's already there. Also plot these 8 data sets to visualize what it looks like and add each plot to this directory and update the PR.
I see the data here in a format like `1.505400000000000000e+04`. Convert it to a format like `15054`. Would be easy to do with some spreadsheet software

2019-06-13 01:45 UTC, CloudyPadmal commented on datasets/eeg-brain-wave-for-confusion/data/demographic_info.csv
> +subject ID, age, ethnicity, gender
Merge this file with `EEG_data.csv` file

2019-06-14 08:43 UTC, CloudyPadmal approved these changes

2019-06-14 09:11 UTC, merged