Play and Stop feature in Focus mode
fossasia/neurolab-android pull request #345
Opened 2019-07-04 10:55 UTC by jddeep

Fixes #343 

**Changes**: Play and Stop feature in Focus mode.

**Screenshot/s for the changes**: 

<img src="" width=200/>

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:

2019-07-05 11:20 UTC, mariobehling requested changes
Please switch the button. Import button should be on the right.

2019-07-05 12:40 UTC, jddeep commented
Done. Thanks.

2019-07-08 06:56 UTC, CloudyPadmal approved these changes

2019-07-08 11:20 UTC, mariobehling approved these changes

2019-07-08 11:20 UTC, merged