Implemented Device Instructions Screen
fossasia/neurolab-android pull request #352
Opened 2019-07-08 06:27 UTC by jddeep

Fixes #349 

**Changes**: Implemented Device Instructions Screen

**Screenshot/s for the changes**: 

<img src="https://user-images.githubusercontent.com/43133646/60787492-92f1a180-a177-11e9-83ab-180e5e940623.png" width=200/>

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:

2019-07-08 06:35 UTC, jddeep commented
@CloudyPadmal @mariobehling Please can we get the previous PRs #345 and #346 merged ASAP (Suggested changes were made to those). Otherwise, build failures will rise and to fix that, I need to push similar changes to new PRs as of previous PRs.

2019-07-08 07:07 UTC, CloudyPadmal requested changes

2019-07-08 07:07 UTC, CloudyPadmal commented on app/src/main/res/values/strings.xml
> +    <string name="step_two_info">Connect the other end of Micro USB to a OTG</string>
```suggestion
    <string name="step_two_info">Connect the other end of Micro USB to an OTG cable</string>
```

2019-07-08 07:07 UTC, CloudyPadmal commented on app/src/main/res/values/strings.xml
> +    <string name="step_three_info">Connect the OTG to the phone</string>
```suggestion
    <string name="step_three_info">Connect the OTG cable to the phone</string>
```

2019-07-08 07:07 UTC, CloudyPadmal commented on app/src/main/res/values/strings.xml
> +    <string name="focus_program_info">This Program Mode helps you increase you increase your focus and concentration levels.</string>
Check this line

2019-07-09 10:02 UTC, mariobehling commented
Thanks, please also resolve conflicts.

2019-07-11 14:54 UTC, CloudyPadmal commented
Conflicts again.

2019-07-11 15:41 UTC, jddeep commented
This can be merged now. Thanks.

2019-07-12 07:29 UTC, merged