Updated focus screen
fossasia/neurolab-android pull request #360
Opened 2019-07-13 23:25 UTC by CoderVishalSehgal

Fixes #354 

**Changes**:
Implemented the Focus screen as per the Neurolab desktop app.

**Screenshot/s for the changes**: 
Video Demo Link:
https://drive.google.com/open?id=1tG89SWEDY3WM5OoTgck676diHGrJ4FxC

**Checklist**: 
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
https://drive.google.com/open?id=1fFlIhSucVv5yB7uvf08ndGSaqrecvT9h

2019-07-13 23:26 UTC, CoderVishalSehgal commented
@jddeep Please have a look here.

2019-07-14 02:55 UTC, jddeep requested changes
We'll need to make some changes.

2019-07-20 07:52 UTC, CloudyPadmal requested changes

2019-07-20 07:52 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
> +
Remove extra lines and reformat the code

2019-07-20 07:52 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
> +
Clean up the code

2019-07-20 07:52 UTC, CloudyPadmal commented on app/src/main/res/layout/fragment_focus_visual.xml
> +            android:background="#A61B1B1B"/>
Move the hardcoded values to resources

2019-07-23 11:02 UTC, CloudyPadmal commented
@CoderVishalSehgal could you please resolve the conflicts? This PR is good to be merged

2019-07-23 11:55 UTC, CloudyPadmal commented
@jddeep can you follow up @CoderVishalSehgal and get the conflict files resolved?

2019-07-24 16:40 UTC, jddeep commented
@CloudyPadmal Just an update: Actually @CoderVishalSehgal has got Associate Developer exam this Sunday, so he is preparing for that. He will be active once again here, when he is done with that, i.e, from next week.
But nevertheless, the changes directed in this PR has been directed by me in PR #365 along with many improvements. So this being remaining unmerged should not be a problem as of now.

2019-07-29 03:09 UTC, jddeep approved these changes

2019-07-30 05:52 UTC, CloudyPadmal approved these changes

2019-07-30 05:52 UTC, merged