Added Toolbar in FeedbackSettings
fossasia/neurolab-android pull request #38
Opened 2019-02-06 03:23 UTC by jddeep

Fixes #37 

**Changes**: Added the Toolbar as ActionBar.

**Screenshot/s for the changes**: 
![screenshot_20190206-085208](https://user-images.githubusercontent.com/43133646/52318881-a04e0880-29ec-11e9-9ca9-be785cf7dcb4.png)

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

2019-02-06 03:30 UTC, jddeep commented
@CloudyPadmal could you please review and merge the PR. Cheers!

2019-02-08 10:09 UTC, jddeep commented
@mariobehling @CloudyPadmal could you please review and merge the PR. Thanks.

2019-02-11 14:10 UTC, jddeep commented
@mariobehling @CloudyPadmal kindly review these pending PRs. They have been sitting for a long time now. Thanks.

2019-02-11 18:18 UTC, CloudyPadmal requested changes

2019-02-11 18:18 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/settings/FeedbackSettings.java
> +        activity.getActionBar().setTitle("Neuro Lab");
Don't use hard-coded resources

2019-02-11 18:18 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/settings/FeedbackSettings.java
> +        //Even if the API level is less than 21 this will work due to
Remove these comments

2019-02-12 09:08 UTC, jddeep commented
@CloudyPadmal Required changes have been seen into. You can now review the PR. Cheers!

2019-02-16 04:10 UTC, jddeep commented
@CloudyPadmal kindly look into the pending PRs and merge them moving ahead. Cheers!

2019-02-24 09:54 UTC, CloudyPadmal approved these changes

2019-02-24 09:54 UTC, merged