Parse channel data from recorded data to process
fossasia/neurolab-android pull request #388
Opened 2019-08-02 14:37 UTC by jddeep

Fixes #387 

**Changes**: Parse channel data from recorded data to process.

**Screenshot/s for the changes**: 
> Not available

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**:

2019-08-02 16:34 UTC, CloudyPadmal reviewed
Why all your PRs are not tracking upstream? It's really confusing to review them. This PR contains all the changes from #385

2019-08-03 01:14 UTC, jddeep commented
Yes, you are right. Actually majorly in my PRs to make new changes, I need stuff from other unmerged PRs to work. But this PR could have been an exception. Thanks will take care from next time.

2019-08-04 11:20 UTC, CloudyPadmal requested changes

2019-08-04 11:20 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
> +    private static String[] parsedData;
Local variable and this one both using the same name. Change to have a different name

2019-08-05 06:06 UTC, CloudyPadmal approved these changes

2019-08-05 06:06 UTC, merged