fix: improved rocket animation and fixed initial startup
fossasia/neurolab-android pull request #408
Opened 2019-08-09 04:20 UTC by adityastic

Fixes #406 

Changes:
- Updated custom view
- fixed fragment startup

Screenshot:
https://drive.google.com/open?id=1-Covc-aG_Yzu4slKl-ZTrSsIms3OjmrC

2019-08-09 14:18 UTC, jddeep requested changes

2019-08-09 14:18 UTC, jddeep commented on app/src/main/java/io/neurolab/main/output/visual/SpaceAnimationVisuals.java
> +        valueAnimator[0].setDuration(500);
If this is responsible for the up animation, then we can make it `900`. Looks less abrupt.

2019-08-10 01:50 UTC, jddeep approved these changes

2019-08-10 02:09 UTC, CloudyPadmal approved these changes

2019-08-10 02:10 UTC, merged