AAB enabled in the app
fossasia/neurolab-android pull request #424
Opened 2019-08-16 08:27 UTC by jddeep

Fixes #401 

**Changes**: AAB enabled in the app

**Screenshot/s for the changes**: 
N/A

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: 
N/A

2019-08-16 10:02 UTC, adityastic requested changes
Change the scripts and not the bundle configuration. Use badge magic for reference

2019-08-16 10:20 UTC, adityastic reviewed
@CloudyPadmal Please make sure that fastlane is initialised in this repository

2019-08-16 14:40 UTC, adityastic commented on app/build.gradle
> +    bundle {
This can be removed completely

2019-08-16 14:41 UTC, adityastic commented on scripts/upload-apk.sh
> +bundle exec fastlane buildAAB
This won't work without you installing fastlane as a bundler

2019-08-16 14:41 UTC, adityastic commented on scripts/upload-apk.sh
> +    fastlane supply --aab neurolab-master-app.aab --skip_upload_apk true --track alpha --json_key ../scripts/fastlane.json --package_name $PACKAGE_NAME
You need to copy it before using it

2019-08-16 14:42 UTC, adityastic commented on fastlane/Fastfile
> +  desc "Submit a new Beta Build to Crashlytics Beta"
Remove the rest of stuff

2019-08-16 14:42 UTC, adityastic commented on fastlane/Appfile
> +json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
Add the json file path, fastlane needs access to it

2019-08-16 15:00 UTC, CloudyPadmal requested changes
We'll add fastlane in a later stage. Just build the appbundle for now.

2019-08-16 15:04 UTC, adityastic commented
@CloudyPadmal he updated the pr with the required files. That's all we need as of now

2019-08-19 08:50 UTC, CloudyPadmal requested changes
Only `./gradlew bundleRelease` is needed in this PR and modify `upload-apk.sh` script to upload that file to apk branch and add it to git lfs.

2019-08-19 08:50 UTC, CloudyPadmal commented on scripts/upload-apk.sh
> +./gradlew bundlePlaystoreRelease
Copy pasted from PSLab right away I guess. This is invalid. Change to `./gradlew bundleRelease`

2019-08-19 08:50 UTC, CloudyPadmal commented on app/build.gradle
> +    bundle {
Not necessary. Remove the whole block.

2019-08-19 09:13 UTC, CloudyPadmal commented
Fixed in #428

2019-08-19 09:13 UTC, closed without merging