Updated Project documentation and features in Readme
fossasia/neurolab-android pull request #427
Opened 2019-08-18 07:24 UTC by jddeep

Fixes #423 

**Changes**: Updated Project documentation and features in Readme

**Screenshot/s for the changes**:
> Check updated README.md once merged

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: 
> Not available

2019-08-18 15:04 UTC, CloudyPadmal requested changes
Why do we have a 12 mb focus.gif file? Make it smaller or remove. It increases the repo size by 13% just for an image.

2019-08-19 08:20 UTC, CloudyPadmal requested changes
Also get all the images down to 200kb

2019-08-19 08:20 UTC, CloudyPadmal commented on README.md
> +  <td><img src = "/docs/images/focus.gif" height = "500" width="250"></td>
Link here, resource missing?

2019-08-19 08:20 UTC, CloudyPadmal commented on README.md
> +<td><img src = "/docs/images/home_screen.png" height = "500" width="250"></td>
Remove spaces inside tags: src = " to src="

This needs to be fixed in many places

2019-08-19 09:02 UTC, CloudyPadmal requested changes
Lot of content corrections need to be made. Can you check with an English teacher or someone fluent in English to double check the content added

2019-08-19 09:02 UTC, CloudyPadmal commented on README.md
> +### Meditation Program mode(under Development)
```suggestion
### Meditation Program mode (Under Development)
```

2019-08-19 09:02 UTC, CloudyPadmal commented on README.md
> +The four major program modes: Focus, Relax, Memory Graph, Meditation.
Put them as a list and set internal hyperlinks

2019-08-19 09:02 UTC, CloudyPadmal commented on README.md
> +The Focus program mode helps the user to increase focus and concentration power through playing games.
Focus program mode helps user increase focus and concentration power by playing games.

2019-08-19 09:02 UTC, CloudyPadmal commented on README.md
> +This is a data visualization mode with the help of graphs, user-friendly stats and a density-spectrum.
user-friendly -> user friendly 
density-spectrum -> density spectrum

2019-08-19 14:58 UTC, jddeep commented on README.md
> +The four major program modes: Focus, Relax, Memory Graph, Meditation.
@CloudyPadmal Internal hyperlinks as of code of those modes or screenshots?

2019-08-19 15:08 UTC, CloudyPadmal commented on README.md
> +The four major program modes: Focus, Relax, Memory Graph, Meditation.
:Sigh: No. https://github.com/aogilvie/markdownLinkTest/blob/master/README.md

2019-08-19 16:46 UTC, CloudyPadmal approved these changes

2019-08-19 16:46 UTC, merged