Added Recorder classes and interface.
fossasia/neurolab-android pull request #45
Opened 2019-02-07 14:38 UTC by jddeep

Fixes #17 partly
**Changes**: Added the recorder classes and interface.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

2019-02-08 10:12 UTC, jddeep commented
@mariobehling @CloudyPadmal please review the PR. Cheers!

2019-02-11 18:45 UTC, CloudyPadmal requested changes

2019-02-11 18:45 UTC, CloudyPadmal commented on app/src/main/java/io/neurolab/SerialRecorder.java
> +//    }
Remove this code

2019-02-12 09:09 UTC, jddeep commented
@CloudyPadmal Required changes have been seen into. You can now review the PR. Cheers!

2019-03-05 08:24 UTC, jddeep commented
@CloudyPadmal Please take a look at the PR. Thanks.

2019-03-21 15:11 UTC, merged