Relax home screen
fossasia/neurolab-android pull request #466
Opened 2019-09-16 11:31 UTC by kshitiz-kumar

Fixes #447

**Changes**: Added Relax home screen

**Screenshot/s for the changes**: <br>
> Relax Home Screen
 
<image src = "https://user-images.githubusercontent.com/38812752/64953866-a456d880-d8a1-11e9-92ec-6c63e7922aa3.png"  width = "200"  height ="350">

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**:

2019-09-16 14:06 UTC, jddeep requested changes

2019-09-16 14:06 UTC, jddeep commented on app/src/main/java/io/neurolab/activities/ProgramModeActivity.java
> +            startActivity(new Intent(this,RelaxParentActivity.class));
Please reformat your code at all places. Use Android studio features of rearrange and reformat for this.

2019-09-16 14:07 UTC, jddeep commented
Also please provide an updated apk for testing.

2019-09-16 18:20 UTC, adityastic requested changes
Provide apk for test

2019-09-16 18:20 UTC, adityastic commented on app/src/main/res/layout/activity_relax_parent.xml
> +            android:scaleType="fitXY"
centerCrop plz

2019-09-16 18:22 UTC, adityastic commented
Please also follow Semantic naming when creating a PR, Reference:
https://github.com/probot/semantic-pull-requests

2019-09-19 16:39 UTC, kshitiz-kumar commented
I have provided the apk for testing also made the changes requested. Also I am new to this open source culture, therefore I really don' t know about the best practices. Any suggestion for that is really appreciated.

2019-09-19 16:51 UTC, kshitiz-kumar commented on app/src/main/res/layout/activity_relax_parent.xml
> +            android:scaleType="fitXY"
@adityastic done

2019-09-20 01:10 UTC, jddeep commented
@kshitiz-kumar The apk is not getting installed. Please upload a correct working apk. Zip the apk file and upload it in the PR description body directly. No need to upload to Google drive.

2019-09-21 05:55 UTC, kshitiz-kumar commented
@jddeep please check the updated aok

2019-09-21 06:05 UTC, jddeep commented
@kshitiz-kumar The apk is still not getting installed. Please check yourself by trying to install the apk you provided.

2019-09-21 06:26 UTC, kshitiz-kumar commented
@jddeep I have installed on three different phone and it is working

2019-09-21 06:40 UTC, jddeep approved these changes
Good job :+1:

2019-09-21 06:40 UTC, merged