Adding release-drafter
fossasia/neurolab-android pull request #477
Opened 2019-09-23 09:36 UTC by Abhik1998

Fixes #463 

**Changes**: Added the GitHub app to this repository following this link https://github.com/apps/release-drafter

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-09-23 09:39 UTC, adityastic commented
@Abhik1998 you need to understand what I'm saying there.

2019-09-23 09:41 UTC, adityastic commented
@jddeep add release drafter to the repo, then merge this

2019-09-23 09:47 UTC, Abhik1998 commented
/assign @jddeep

2019-09-23 10:10 UTC, adityastic requested changes
Squash into a single commit

2019-09-23 10:12 UTC, adityastic commented
Also, use this file as a template: https://github.com/fossasia/badge-magic-android/blob/development/.github/release-drafter.yml

2019-09-23 10:47 UTC, Abhik1998 commented
@adityastic I used that .

2019-09-23 10:52 UTC, adityastic commented
@Abhik1998 please check the file I linked to. It's different

2019-09-23 11:19 UTC, adityastic requested changes
Squash into a single commit

2019-09-23 11:22 UTC, Abhik1998 commented
/retest

2019-09-23 18:42 UTC, CloudyPadmal requested changes

2019-09-23 18:42 UTC, CloudyPadmal commented on .github/release-drafter.yml
> +      - 'bugfix'
Only use labels that are available (https://github.com/fossasia/neurolab-android/labels)

2019-09-29 02:12 UTC, jddeep commented
@Abhik1998 builds and checks are failing. Also, you didn't make the changes asked. Any updates on this?

2019-09-29 08:06 UTC, Abhik1998 commented
> @Abhik1998 builds and checks are failing. Also, you didn't make the changes asked. Any updates on this?

Ohh sorry, I was at home so I was unable to work there. I have resolved the earlier issue. I used a label that was not recognized hence this was the error.

2019-09-29 08:15 UTC, Abhik1998 commented
@jddeep  please have a review

2019-09-30 05:02 UTC, CloudyPadmal approved these changes

2019-09-30 08:39 UTC, adityastic approved these changes

2019-09-30 08:39 UTC, adityastic commented
@jddeep ready to merge :+1:

2019-09-30 08:41 UTC, merged