Focus Landscape orientation
fossasia/neurolab-android pull request #481
Opened 2019-09-26 15:14 UTC by kshitiz-kumar

Fixes #473 

**Changes**: Added the Focus Landscape Orientation

**Screenshot/s for the changes**:
<img src="https://user-images.githubusercontent.com/38812752/65700022-96246b80-e09c-11e9-8c65-9d3702564284.jpeg" height=200>
<image src="https://user-images.githubusercontent.com/38812752/65700030-97ee2f00-e09c-11e9-83c0-36f8a6bf4627.jpeg" height=200>
<br>
>>
<img src="https://user-images.githubusercontent.com/38812752/65700608-907b5580-e09d-11e9-9295-a08b319a9cff.gif"  height=600>

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: 
[app-debug.zip](https://github.com/fossasia/neurolab-android/files/3658498/app-debug.zip)

2019-09-26 17:20 UTC, kshitiz-kumar commented
@jddeep why is that I am getting negative result for Codacy/PR quality review.

2019-09-27 04:04 UTC, jddeep requested changes

2019-09-27 04:04 UTC, jddeep commented on app/src/main/res/layout-land/activity_focus_parent.xml
> +            android:layout_height="200dp"
Remove hardcoding.

2019-09-27 04:04 UTC, jddeep commented on app/src/main/res/layout-land/activity_focus_parent.xml
> +<?xml version="1.0" encoding="utf-8"?>
Rearrange and reformat the code. Remove hardcoding and unnecessary extra blank lines.

2019-09-27 17:28 UTC, kshitiz-kumar commented
@jddeep review please.

2019-09-28 18:20 UTC, kshitiz-kumar commented
@jddeep please review this.

2019-09-29 02:07 UTC, jddeep approved these changes

2019-09-29 02:07 UTC, merged