Settings Landscape Mode Added
fossasia/neurolab-android pull request #491
Opened 2019-10-02 16:04 UTC by amilaneni99

Issue No #483

Fixes #[Add issue number here. Note: This will automatically closes the issue. If you do not solve the issue entirely, please change the message to e.g. "First steps for issues #IssueNumber]

**Changes**: [Add here what changes were made in this issue and if possible provide links.]

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration. Use `<img src="paste-url-here" width=200/>` to add images]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

2019-10-02 16:40 UTC, amilaneni99 commented
![output](https://user-images.githubusercontent.com/34275469/66063643-6fb17500-e561-11e9-891f-d982f7e7fcc1.gif)
This is the output. The landscape mode is working fine.

2019-10-03 05:53 UTC, dipu989 commented
@amilaneni99 
Please upload Apk for testing and remove the extra text from PR description. Please have a look at any merged PR, you will get the idea.

2019-10-03 06:28 UTC, CloudyPadmal commented
Also resize the uploaded images to fit in screen. Check and fix the issues reported by Travis CI

2019-10-03 06:47 UTC, amilaneni99 commented
> Also resize the uploaded images to fit in screen. Check and fix the issues reported by Travis CI

I resized the Screenshot and fixed the PR description. 
The error in Travic CI says this:
_java.lang.IllegalArgumentException: Cannot find JAR 'slf4j-api-1.7.25.jar' required by module 'gradle-launcher' using classpath or distribution directory '/home/travis/.gradle/wrapper/dists/gradle-5.1.1-all/97z1ksx6lirer3kbvdnh7jtjg/gradle-5.1.1'_

I didn't change any other file except the new XML file. It would be nice if you can look into this error. Thanks

2019-10-09 12:04 UTC, jddeep approved these changes

2019-10-12 14:10 UTC, jddeep commented
@amilaneni99 Please pull latest changes and rerun the build here. Thanks.

2019-10-13 06:12 UTC, CloudyPadmal requested changes

2019-10-13 06:12 UTC, CloudyPadmal commented on app/src/main/res/layout-land/activity_settings.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
Reformat the code here

2019-10-13 06:36 UTC, amilaneni99 commented on app/src/main/res/layout-land/activity_settings.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
Is there an issue here?

2019-10-17 06:35 UTC, jddeep commented on app/src/main/res/layout-land/activity_settings.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
@amilaneni99 Use Android studio code reformatting options available to use.

2019-10-17 07:04 UTC, CloudyPadmal commented
Btw do we need an explicit land layout for landscape? Unless there's a difference between landscape implementation with portrait, Android handles it automatically right?

2019-10-18 07:17 UTC, kshitiz-kumar commented
> Btw do we need an explicit land layout for landscape? Unless there's a difference between landscape implementation with portrait, Android handles it automatically right?

Yes, android handles it automatically. But this issue has been opened because we need a different behaviour in landscape mode than the portrait.

This happens when you operate settings in landscape mode.
<img src="https://user-images.githubusercontent.com/38812752/67073695-46215c00-f1a5-11e9-9363-29be039060ab.jpeg"  width = 200>

2020-01-15 14:37 UTC, adityastic commented
Updates?

2020-01-15 15:06 UTC, kshitiz-kumar commented
> Updates?

I think the issue has been resolved @adityastic

2020-01-15 15:15 UTC, adityastic commented
> > Updates?
> 
> I think the issue has been resolved @adityastic

The CI is failing

2020-01-15 15:28 UTC, kshitiz-kumar commented
> > > Updates?
> > 
> > 
> > I think the issue has been resolved @adityastic
> 
> The CI is failing

I think someone else has referenced the PR and that has been closed. Otherwise you can check the setting its working correctly

2020-01-29 11:51 UTC, closed without merging