Minor typo fixes
fossasia/neurolab-android pull request #529
Opened 2019-11-06 21:47 UTC by Rajchowdhury420

Fixes  #528

**Changes**: [Few minor typos fixed in README]

**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration. Use `<img src="paste-url-here" width=200/>` to add images]

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [ ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ ] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [ ] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

2019-11-07 06:11 UTC, dipu989 requested changes

2019-11-07 06:11 UTC, dipu989 commented on README.md
> +This repository holds the Android app for the Neurolab Hardware. We are developing a neuro-device as a headband with integrated electronics. The goal of the Neurolab project is to create an easy way
Please remove "way". "easy to use" is quoting that hardware can be used easily!

2019-11-07 06:15 UTC, dipu989 commented
@Rajchowdhury420 Also, fill information in the template of the PR correctly. 
Take a look at https://github.com/fossasia/pslab-android/pull/1993.

2019-11-07 06:46 UTC, RajChowdhury240 reviewed
Fixed Minor typos

2019-11-07 07:00 UTC, Rajchowdhury420 commented
@dipu989 check nah

2019-11-10 07:38 UTC, mariobehling commented
Thanks. We need to move forward with the functionality though right now. Improving typos can also be done as part of improving functionality. Please help to focus on code.

2019-11-12 02:53 UTC, jddeep approved these changes
Thanks. Let us move from here. Please focus on features and code for now.

2019-11-12 02:53 UTC, merged