fix: #538 Add unregisterReceiver() missing in some fragments
fossasia/neurolab-android pull request #539
Opened 2019-11-14 11:26 UTC by dheerajkotwani

Fixes: #538 Add unregisterReceiver() missing in some fragments

**Changes**: unregisterReceiver() is added to MemoryGraphFragment and FocusVisualFragment

**Checklist**:
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-11-15 14:28 UTC, rob729 approved these changes

2019-11-15 17:23 UTC, CloudyPadmal approved these changes

2019-11-16 16:19 UTC, jddeep commented
What is this? Why are we registering and unregistering receivers everywhere? It is already being done in `Neurolab` activity? :thinking:

2019-11-16 16:20 UTC, jddeep commented
We need to register the receiver only once in the app and use it elsewhere.

2019-11-16 16:20 UTC, jddeep requested changes
We need to register the receiver only once in the app and use it elsewhere.

2019-11-16 16:39 UTC, dheerajkotwani commented
@jddeep when we try to come out of the FocusVisualFragment it showed Log that unregisterReceivers are missing

2019-11-17 02:26 UTC, jddeep requested changes

2019-11-17 02:26 UTC, jddeep commented on app/src/main/java/io/neurolab/fragments/FocusVisualFragment.java
> +            getContext().registerReceiver(dataReceiver, intentFilter);
The receiver will be again registered on resume and data transmission will start all over again with new intent filter and perms. Let's not do any of these changes right now.

2019-11-17 02:27 UTC, jddeep commented
Closing this.

2019-11-17 02:27 UTC, closed without merging