Refactored the File Organization correctly
fossasia/neurolab-android pull request #54
Opened 2019-02-18 04:34 UTC by suresh-gandhi

Fixes #52 

**Changes**: 
* Placed all the classes in correct subpackage/package. Moreover, the behavior is refactored taking into account that the external changes don't alter the internal structure of the application.
* The changes are taken following the neurolab-desktop's standards (which is the software system we are porting) and for helping in better code organization in the long-run.

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

2019-02-18 04:42 UTC, suresh-gandhi commented
@mariobehling @CloudyPadmal Could you please review the PR?

2019-03-01 18:28 UTC, CloudyPadmal approved these changes

2019-03-01 18:28 UTC, CloudyPadmal requested changes
Changes are all good. But there are conflicts to resolve first

2019-03-14 20:14 UTC, suresh-gandhi commented
@CloudyPadmal I have resolved the conflicts. Could you please review the PR. Conflicts came due to the lag of my branch behind the development branch(because of subsequent PR's). Rebasing solved the issue. I have also squashed them into a single commit. Just let me know if anything else needs to be changed.

2019-03-22 15:23 UTC, iamareebjamal commented on app/src/main/java/io/neurolab/main/NeuroSettings.java
> +package io.neurolab.main;
Shouldn't this be in settings?

2019-03-22 15:23 UTC, iamareebjamal commented on app/src/main/java/io/neurolab/model/FeedbackSettings.java
> +package io.neurolab.model;
Shouldn't this be in settings?

2019-05-13 04:55 UTC, suresh-gandhi commented
@CloudyPadmal resolved the conflicts. Could you please review and merge. Let me know if something else needs to be changed.

2019-05-13 09:06 UTC, mariobehling approved these changes

2019-05-13 09:06 UTC, merged