Add navigate up button in fragment_feedback_settings #issue 66
fossasia/neurolab-android pull request #67
Opened 2019-03-02 05:59 UTC by itsSiddharthGupta

Fixes #66 

**Changes**:Added back button on the toolbar.
**Screenshot/s for the changes**: 
![screenshot_2019-03-02-11-11-47-74](https://user-images.githubusercontent.com/36455409/53677841-5ea73980-3cdc-11e9-91a4-678ba861dd03.png)

**Checklist**: [Please tick following check boxes with `[x]` if the respective task is completed]
- [ ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [ ] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [app-debug.zip](https://github.com/fossasia/neurolab-android/files/2921794/app-debug.zip)

2019-03-02 06:06 UTC, itsSiddharthGupta commented
@mariobehling  @CloudyPadmal  Please take a look and review it...

2019-03-02 06:09 UTC, jddeep requested changes
Remove the comments and extra line above that.

2019-03-02 06:39 UTC, itsSiddharthGupta commented
@jddeep please review it now.. And thank you :)

2019-03-02 07:28 UTC, CloudyPadmal submitted a review, later dismissed

2019-03-02 10:03 UTC, itsSiddharthGupta commented
Thanks for approving it @CloudyPadmal 
I want to know when is this PR will get merged?

2019-03-02 10:12 UTC, jddeep requested changes
Please squash your commits into one. Thanks.

2019-03-02 10:17 UTC, itsSiddharthGupta commented
> 
> 
> Please squash your commits into one. Thanks.

@jddeep Can you please tell me how can i squash my commits because i've never tried this before ...

2019-03-02 10:51 UTC, itsSiddharthGupta commented
@CloudyPadmal  I've squashed commits into 1. Please review it now!!  :-)

2019-03-02 15:48 UTC, itsSiddharthGupta commented
@mariobehling Please review it..

2019-03-02 16:11 UTC, jddeep approved these changes

2019-03-03 02:56 UTC, CloudyPadmal approved these changes

2019-03-03 02:56 UTC, merged