Ported the BaselineCorrectionFunction functionality from neurolab-desktop
fossasia/neurolab-android pull request #82
Opened 2019-03-15 17:50 UTC by RohitJain1103

Fixes #17 partially.

**Changes**: 
Ported the independent BaselineCorrectionFunction class and placed it in the appropriate subpackage(io.neurolab.tools) following the neurolab-desktop's standards.

**Checklist**:
- [x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x] No modifications are done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x] I have reformatted code in every file included in this PR [<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>L</kbd>]
- [x] My code does not contain any extra lines or extra spaces
- [x] I have requested reviews from other members

**APK for testing**: [Compress the `app-debug.apk` file into a `<feature>.rar` or `<feature>.zip` file and upload it here]

2019-03-15 17:52 UTC, RohitJain1103 commented
@CloudyPadmal @mariobehling could you please review the PR?

2019-03-16 01:43 UTC, jddeep commented on build.gradle
> +    minSdkVersion = 24
We should support from API level 16

2019-03-16 15:47 UTC, suresh-gandhi reviewed
@RohitJain1103 I would suggest you to annotate your methods/classes(which enforces an upgrade) with the TargetApi.

2019-03-16 15:54 UTC, RohitJain1103 commented
> @RohitJain1103 I would suggest you to annotate your methods/classes(which enforces an upgrade) with the TargetApi.
 @suresh-gandhi Okay. Thanks.

2019-03-16 17:05 UTC, suresh-gandhi approved these changes

2019-03-18 13:33 UTC, jddeep requested changes

2019-03-18 13:33 UTC, jddeep commented on app/src/main/java/io/neurolab/tools/BaselineCorrectionFunction.java
> +@TargetApi(24)
This makes this complete class unfunctional and not usable below API 24. Please change.

2019-03-19 05:56 UTC, Dev-Aslan commented
Hi I am Devbrat From India
I Also want to contribute to this project, can anyone please tell me where to start from?

2019-03-19 10:20 UTC, RohitJain1103 commented
Please join the following gitter chat - https://gitter.im/fossasia/fossasia . You can get started with any project. Just start with a small issue and try to fix it.

2019-03-21 15:18 UTC, merged